### ISSUE TITLE
Bug: cfgrid is not available in Anaconda packages repository

### ISSUE THREAD

**Issue by garm005** [cemanetwork/appmar#5]
Hi, I have tried to install Appmar on my computer (Windows 10). I created the Appmar environment and tried to download all the packages. The only problem I had, it was related to cfgrid package, I got this:

Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cfgrid

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/r/win-64
  - https://conda.anaconda.org/r/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I tried to install the package, again, with this command:
conda install --name appmarenv -c conda-forge cfgrid
But, I got the same error message.

Using pip, I could install cfgrid:
pip install cfgrib

We should test the cfgrid installation package, using the conda-forge channel, again. If the package is not available in the repository, we should say that Weibull and cfgrid requires the use of pip.

**Comment by dact221** [comment]
The name of the package is `cfgrib` not `cfgrid`. It is a Python interface to map GRIB (GRIdded Binary) files to NetCDF. cfgrib is maintained by the European Centre for Medium-Range Weather Forecasts (ECMWF). They provide installation instructions via Conda:

https://github.com/ecmwf/cfgrib#installation

They also state that if you install the package using pip, you must install binary dependencies yourself.
